name: Build and publish docker image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
    
      - name: Build with JIB
        run: |
          ./gradlew jib \
          -Djib.to.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
